#!/bin/bash

# Collecting system information
USERNAME=$(whoami)
DATE_TIME=$(date +"%Y-%m-%d %H:%M:%S")
HOSTNAME=$(hostname)
OS=$(grep "^PRETTY_NAME=" /etc/os-release | cut -d= -f2 | tr -d '"')
UPTIME=$(uptime -p)

# Hardware Information
CPU=$(lscpu | grep "Model name" | awk -F': ' '{print $2}')
RAM=$(free -h | awk '/^Mem:/ {print $2}')
DISK=$(lsblk -d -o MODEL,SIZE | tail -n +2)
VIDEO=$(lshw -class display | grep "product" | awk -F': ' '{print $2}')

# Network Information
FQDN=$(hostname --fqdn)
HOST_IP=$(ip -4 a show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -n 1)
GATEWAY_IP=$(ip route | grep default | awk '{print $3}')
DNS_SERVER=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd "," -)

# System Status
USERS_LOGGED_IN=$(who | awk '{print $1}' | sort | uniq | paste -sd ", ")
DISK_SPACE=$(df -h --output=target,avail -x tmpfs -x devtmpfs | tail -n +2)
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ //')
LISTENING_PORTS=$(ss -tuln | awk '{print $5}' | grep -Eo '[0-9]+$' | sort -u | paste -sd ", ")
UFW_STATUS=$(sudo ufw status | grep "Status" | awk '{print $2}')

# Generating report
cat <<EOF

System Report generated by $USERNAME, $DATE_TIME

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
RAM: $RAM
Disk(s):
$DISK
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_IP
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $USERS_LOGGED_IN
Disk Space:
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS

EOF
